import 'package:get/get_navigation/src/root/internacionalization.dart';

class AppTranslation extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en': {
      "app_name": "Test theme and language",
      "choose": "Choose Your Language",
      "select": "Select your preferred language to get started",
      "next": "Next",
      "login": "Log In",
      "forget": "Forgot Password?",
      "dontHaveAccount": "Don’t have account?",
      "signup": "Sign Up",
      "alreadyHaveAndAccount": "Already have an account?",
      "start": "Start",
      "sendOTP": "Send OTP",
      "enterOTP": "Enter OTP",
      "verify": "Verify",
      "new_Password": "Set New Password",
      "changeNow": "Change Now",
      "letSetUpProfile": "Let’s Set Up Your User Profile",
      "quickEran": "A few quick steps to start earning with us",
      "Confrim": "Confirm & Continue",
      "verifyIdentity": "Verify Your Identity",
      "quickSelfie": "Take a quick selfie to complete your profile",
      "verificationSuccessful": "Verification Successful",
      "bookRide": "Book a Ride",
      "sendParcel": "Send Parcel",
      "recentDestination": "Recent Destination",
      "needHelp": "Need Help?",
      "support": "Chat with our support",
      "confirm": "Confirm",
      "cancel": "Cancel",
      "searching": "We’re searching a request for you!",
      "save": "Save Now",
      "liveChat": "Live Chat",
      "logOut": "Log Out",
      "doYouHaveLogOut": "Do you have Log Out ?",
      "proceed": "Proceed",
      "youareNowOffline": "You are now Offline",
      "decline": "Decline",
      "accept": "Accept",
      "newRideRequest": "New Ride Request",
    },
    'pt': {
      "app_name": "Teste tema e idioma",
      "choose": "Escolha seu idioma",
      "select": "Selecione seu idioma preferido para começar",
      "next": "Próximo",
      "login": "Entrar",
      "forget": "Esqueceu a senha?",
      "dontHaveAccount": "Não tem uma conta?",
      "signup": "Registrar-se",
      "alreadyHaveAndAccount": "Já tem uma conta?",
      "start": "Iniciar",
      "sendOTP": "Enviar OTP",
      "enterOTP": "Digite o OTP",
      "verify": "Verificar",
      "new_Password": "Definir nova senha",
      "changeNow": "Mudar agora",
      "letSetUpProfile": "Vamos configurar seu perfil",
      "quickEran": "Alguns passos rápidos para começar a ganhar conosco",
      "Confrim": "Confirmar e continuar",
      "verifyIdentity": "Verifique sua identidade",
      "quickSelfie": "Tire uma selfie rápida para completar seu perfil",
      "verificationSuccessful": "Verificação bem-sucedida",
      "bookRide": "Reservar uma corrida",
      "sendParcel": "Enviar pacote",
      "recentDestination": "Destino recente",
      "needHelp": "Precisa de ajuda?",
      "support": "Converse com nosso suporte",
      "confirm": "Confirmar",
      "cancel": "Cancelar",
      "searching": "Estamos procurando um motorista para você!",
      "save": "Salvar agora",
      "liveChat": "Chat ao vivo",
      "logOut": "Sair",
      "doYouHaveLogOut": "Deseja sair?",
      "proceed": "Prosseguir",
      "youareNowOffline": "Você está offline agora",
      "decline": "Recusar",
      "accept": "Aceitar",
      "newRideRequest": "Nova solicitação de corrida",
    },
  };
}
